# cargo +nightly fmt
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 120
merge_derives = false
newline_style = "Unix"
reorder_imports = true
unstable_features = true
use_small_heuristics = "Max"
