#!/bin/bash
## Copyright (c) Huawei Technologies Co., Ltd. 2023. All rights reserved.
# KubeOS is licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#     http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
## See the Mulan PSL v2 for more details.

if [[ $EUID -ne 0  ]]; then
    echo "please use root to run hostshell"
    exit 1
fi

ROOT_FS_PATH="/proc/${PPID}/root"
BASH_PATH="/usr/bin/bash"

nsenter -t 1 -a "${ROOT_FS_PATH}${BASH_PATH}"
